# Generated by Django 2.0.3 on 2018-12-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=25, verbose_name='Müşteri Telefon Numarı'),
        ),
    ]
