# Generated by Django 2.0.3 on 2018-12-08 18:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20181208_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='from_email',
            field=models.CharField(max_length=25, verbose_name='Lütfen Emailiniz Giriniz'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='Lütfen Bizden İstediğniz Hizmeti Belirtin'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=25, verbose_name='Lütfen İsinizi Giriniz.'),
        ),
    ]
