# Generated by Django 2.0.3 on 2018-11-30 18:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=25, verbose_name='Müşteri İsim Soyisim')),
                ('account_type', models.CharField(max_length=25, verbose_name='Kategori')),
                ('account_area', models.CharField(max_length=25, verbose_name='Bölge')),
                ('account_phone', phone_field.models.PhoneField(blank=True, help_text='Müşteri Number', max_length=31)),
                ('account_information', ckeditor.fields.RichTextField(verbose_name='Müşteri Notları')),
                ('account_created', models.DateTimeField(auto_now=True, verbose_name='Kayıt Tarihi.')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
    ]
