# Generated by Django 2.0.3 on 2018-11-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_phone',
        ),
    ]
