# Generated by Django 2.0.3 on 2018-11-30 18:45

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_account_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Müşteri Number', max_length=31),
        ),
    ]
